# Generated by Django 3.2.7 on 2021-09-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='modifield_at',
            new_name='modified_at',
        ),
    ]
